config/routes.rb
Rails.application.routes.draw do
  resources :desserts
  resources :enums
  devise_for :users

  root "boards#index"

  resources :boards do
    resources :comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  require 'carrierwave/orm/activerecord'

  validates_presence_of :user_id

  belongs_to :user
  has_many :comments

  mount_uploader :avatar, AvatarUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board
end

app/models/dessert.rb
class Dessert < ApplicationRecord
  enum status: [:coffee, :tea, :juice, :icecream]
end

app/models/enum.rb
class Enum < ApplicationRecord
  enum status: [:coffee, :tea, :juice, :icecream]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :boards
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1 or /boards/1.json
  def show
      @comment = Comment.new
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    if user_signed_in?
      @board = Board.new(board_params)
      @board.user_id = current_user.id

      respond_to do |format|
        if @board.save
          format.html { redirect_to @board, notice: "Board was successfully created." }
          format.json { render :show, status: :created, location: @board }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @board.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to '/users/sign_in'
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    if @board.user_id == current_user.id
      respond_to do |format|
        if @board.update(board_params)
          format.html { redirect_to @board, notice: "Board was successfully updated." }
          format.json { render :show, status: :ok, location: @board }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @board.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to @board
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    if @board.user_id == current_user.id
      @board.destroy
      respond_to do |format|
        format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to @board
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:title, :content, :avatar)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_board

  def create
    comment = @board.comments.new(comments_params)
    comment.user_id = current_user.id
    comment.save

    redirect_to @board
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    comment = Comment.find(params[:id])

    if comment.user_id == current_user.id
      comment.update(comments_params)
    end

    redirect_to @board
  end

  def destroy
    comment = Comment.find(params[:id])

    if comment.user_id == current_user.id
      comment.destroy

      redirect_to @board
    end
  end

  private
  def set_board
    @board = Board.find(params[:board_id])
  end

  def comments_params
    params.require(:comment).permit(:content, :user_id)
  end
end

app/controllers/desserts_controller.rb
class DessertsController < ApplicationController
  before_action :set_dessert, only: %i[ show edit update destroy ]

  # GET /desserts or /desserts.json
  def index
    @desserts = Dessert.all
  end

  # GET /desserts/1 or /desserts/1.json
  def show
  end

  # GET /desserts/new
  def new
    @dessert = Dessert.new
  end

  # GET /desserts/1/edit
  def edit
  end

  # POST /desserts or /desserts.json
  def create
    @dessert = Dessert.new(dessert_params)

    respond_to do |format|
      if @dessert.save
        format.html { redirect_to @dessert, notice: "Dessert was successfully created." }
        format.json { render :show, status: :created, location: @dessert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dessert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /desserts/1 or /desserts/1.json
  def update
    respond_to do |format|
      if @dessert.update(dessert_params)
        format.html { redirect_to @dessert, notice: "Dessert was successfully updated." }
        format.json { render :show, status: :ok, location: @dessert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dessert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desserts/1 or /desserts/1.json
  def destroy
    @dessert.destroy
    respond_to do |format|
      format.html { redirect_to desserts_url, notice: "Dessert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dessert
      @dessert = Dessert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dessert_params
      params.require(:dessert).permit(:title, :content, :status)
    end
end

app/controllers/enums_controller.rb
class EnumsController < ApplicationController
  before_action :set_enum, only: %i[ show edit update destroy ]

  # GET /enums or /enums.json
  def index
    @enums = Enum.all
  end

  # GET /enums/1 or /enums/1.json
  def show
  end

  # GET /enums/new
  def new
    @enum = Enum.new
  end

  # GET /enums/1/edit
  def edit
  end

  # POST /enums or /enums.json
  def create
    @enum = Enum.new(enum_params)

    respond_to do |format|
      if @enum.save
        format.html { redirect_to @enum, notice: "Enum was successfully created." }
        format.json { render :show, status: :created, location: @enum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enums/1 or /enums/1.json
  def update
    respond_to do |format|
      if @enum.update(enum_params)
        format.html { redirect_to @enum, notice: "Enum was successfully updated." }
        format.json { render :show, status: :ok, location: @enum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enums/1 or /enums/1.json
  def destroy
    @enum.destroy
    respond_to do |format|
      format.html { redirect_to enums_url, notice: "Enum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enum
      @enum = Enum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enum_params
      params.require(:enum).permit(:title, :content, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/desserts_helper.rb
module DessertsHelper
end

app/helpers/enums_helper.rb
module EnumsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.file_field :avatar %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<%if @board.user_id == current_user.id %>
  <h1>Editing Board</h1>

  <%= render 'form', board: @board %>

  <%= link_to 'Show', @board %> |
  <%= link_to 'Back', boards_path %>

<%else %>
  <P>게시물 수정 권한이 없습니다.</P>
  <%= link_to 'back', boards_path %>

<% end %>

app/views/boards/index.html.erb
<div class="container">
<!--  <ul id="nav">-->
<!--    <li><a href="">메인메뉴1</a>-->
<!--      <ul>-->
<!--        <li><a href="">1-1</a></li>-->
<!--        <li><a href="">1-2</a></li>-->
<!--        <li><a href="">1-3</a></li>-->
<!--      </ul>-->
<!--    </li>-->
<!--    <li><a href="">메인메뉴2</a>-->
<!--      <ul>-->
<!--        <li><a href="">2-1</a></li>-->
<!--        <li><a href="">2-2</a></li>-->
<!--        <li><a href="">2-3</a></li>-->
<!--        <li><a href="">2-4</a></li>-->
<!--      </ul>-->
<!--    </li>-->
<!--    <li><a href="">메인메뉴3</a>-->
<!--      <ul>-->
<!--        <li><a href="">3-1</a></li>-->
<!--        <li><a href="">3-2</a></li>-->
<!--      </ul>-->
<!--    </li>-->
<!--  </ul>-->
</div>



<p id="notice"><%= notice %></p>

<h1>Boards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.title %></td>
        <td><%= board.content %></td>
        <td><%= board.user.name rescue "이름없음" %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Destroy', board, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if user_signed_in? %>
  <%= link_to 'New Board', new_board_path %>
<%else %>
  <%= link_to 'New Board', new_user_session_path%>
<%end %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @board.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @board.content %>
</p>

<p>
  <%= image_tag(@board.avatar.url) rescue '' %>
</p>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_board_path(@board) %> |
  <%= link_to 'Destroy', board_path, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>

<%= link_to 'Back', boards_path %>

<P>
  <h3>Comments</h3>
    <div id="comments">
      <%= render @board.comments %>
    </div>

    <%if user_signed_in?%>
      <div>
        <%= render 'comments/new', board: @board, comment: Comment.new %>
      </div>
    <% end %>
</p>

app/views/comments/_comment.html.erb
<p>
  <div id="comment_<%=comment.id %>">
    <%= comment.content %> -- <%= comment.created_at.to_s(:long) %>

    <% if user_signed_in? %>
      <%= link_to 'Edit', edit_board_comment_path(id: comment.id, board_id: comment.board.id, user_id: comment.user.id), remote: true %>
      <%= link_to 'Destroy', board_comment_path(id: comment.id, board_id: comment.board.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</p>

app/views/comments/_edit.html.erb
<%=form_for([@board, @comment], remote: true) do |form| %>
  Edit Comment: <br>
  <%= form.text_area :content %>
  <%= form.submit %>
<% end %>

app/views/comments/_new.html.erb
<%= form_for([@board, Comment.new], remote: true) do |form| %>
  Your Comment: <br>
  <%= form.text_area :content %> <br>
  <%= form.submit %>
<% end %>

app/views/comments/edit.js.erb
var elem = document.querySelector('#comment_<%=@comment.id %>');

elem.innerHTML = '<%= j render 'edit' %>';

app/views/desserts/_form.html.erb
<%= form_with(model: dessert, local: true) do |form| %>
  <% if dessert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dessert.errors.count, "error") %> prohibited this dessert from being saved:</h2>

      <ul>
        <% dessert.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/desserts/edit.html.erb
<h1>Editing Dessert</h1>

<%= render 'form', dessert: @dessert %>

<%= link_to 'Show', @dessert %> |
<%= link_to 'Back', desserts_path %>

app/views/desserts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Desserts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @desserts.each do |dessert| %>
      <tr>
        <td><%= dessert.title %></td>
        <td><%= dessert.content %></td>
        <td><%= dessert.status %></td>
        <td><%= link_to 'Show', dessert %></td>
        <td><%= link_to 'Edit', edit_dessert_path(dessert) %></td>
        <td><%= link_to 'Destroy', dessert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dessert', new_dessert_path %>

app/views/desserts/new.html.erb
<h1>New Dessert</h1>

<%= render 'form', dessert: @dessert %>

<%= link_to 'Back', desserts_path %>

app/views/desserts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @dessert.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @dessert.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @dessert.status %>
</p>

<%= link_to 'Edit', edit_dessert_path(@dessert) %> |
<%= link_to 'Back', desserts_path %>

app/views/enums/_form.html.erb
<%= form_with(model: enum, local: true) do |form| %>
  <% if enum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enum.errors.count, "error") %> prohibited this enum from being saved:</h2>

      <ul>
        <% enum.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enums/edit.html.erb
<h1>Editing Enum</h1>

<%= render 'form', enum: @enum %>

<%= link_to 'Show', @enum %> |
<%= link_to 'Back', enums_path %>

app/views/enums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enums.each do |enum| %>
      <tr>
        <td><%= enum.title %></td>
        <td><%= enum.content %></td>
        <td><%= enum.status %></td>
        <td><%= link_to 'Show', enum %></td>
        <td><%= link_to 'Edit', edit_enum_path(enum) %></td>
        <td><%= link_to 'Destroy', enum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enum', new_enum_path %>

app/views/enums/new.html.erb
<h1>New Enum</h1>

<%= render 'form', enum: @enum %>

<%= link_to 'Back', enums_path %>

app/views/enums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @enum.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @enum.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @enum.status %>
</p>

<%= link_to 'Edit', edit_enum_path(@enum) %> |
<%= link_to 'Back', enums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tistory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%if user_signed_in? %>
      <%=current_user.email %>
      <%=link_to 'Log Out', destroy_user_session_path, method: :delete %>
    <%else%>
      <%=link_to 'Sign Up', new_user_registration_path %>
      <%=link_to 'Sign In', new_user_session_path %>
    <%end%>

    <%= yield %>
  </body>
</html>